site_name: Velora
site_description: A Liquid Reinforcement Learning (RL) framework
site_url: https://velora.achronus.dev/

theme:
  name: "material"
  language: en
  palette:
    scheme: slate
    primary: blue
    accent: cyan
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  logo: assets/imgs/logo.png
  favicon: favicon.png
  icon:
    repo: fontawesome/brands/github

repo_name: Achronus/velora
repo_url: https://github.com/Achronus/velora
edit_uri: edit/main/docs

extra_css:
  - "assets/css/icons.css"
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - "assets/js/katex.js"
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

nav:
  - Velora: index.md
  - Getting Started:
      - Getting Started: starting/index.md
      - Roadmap: starting/roadmap.md
      - Appreciation: starting/homage.md
      - Brief History & Motivation: starting/history.md
      - License: starting/license.md
  - Learn:
      - User Guide - Tutorials:
          - User Guide - Tutorials: learn/tutorial/index.md
          - DDPG: learn/tutorial/ddpg.md
          # - Gymnasium: learn/tutorial/gym.md
          # - Utilities: learn/tutorial/utils.md
      - Customization:
          - Customization: learn/customize/index.md
          - Wiring: learn/customize/wiring.md
          - Liquid Networks: learn/customize/liquid.md
          - Buffers: learn/customize/buffers.md
          - Actor-Critics: learn/customize/acs.md
          # - Backbones: learn/customize/backbone.md
      - Theory:
          - Theory: learn/theory/index.md
          - Liquid Neural Networks: learn/theory/lnn.md
      - API Reference:
          - API Reference: learn/reference/index.md
          - models: 
            - lnn: learn/reference/models/lnn.md
            - ddpg: learn/reference/models/ddpg.md
            - activation: learn/reference/models/activation.md
            - backbone: learn/reference/models/backbone.md
          - buffer: learn/reference/buffer.md
          - gymnasium: learn/reference/gym.md
          - noise: learn/reference/noise.md
          - utils: learn/reference/utils.md
          - wiring: learn/reference/wiring.md
  - Help: help.md
  - Changelog: 
      - v0.0.2 (Beta): changelog/v0.0.2.md
      - v0.0.1 (Alpha): changelog/v0.0.1.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Achronus/velora
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/velora

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/assets/icons
  - pymdownx.highlight:
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      title: Page Contents

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [velora]
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [std, py]
            - url: https://pytorch.org/docs/stable/objects.inv
            - url: https://docs.pydantic.dev/latest/objects.inv
            - url: https://gymnasium.farama.org/objects.inv
          options:
            annotations_path: source
            show_source: true
            show_root_toc_entry: false
            show_object_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_object_full_path: false
            docstring_style: google
