[project]
name = "velora"
version = "0.3.0"
description = "A Reinforcement Learning (RL) research framework for lightweight, scalable, transparent, and stateful agents."
authors = [{ name = "Ryan Partridge", email = "codemonkey37@proton.me" }]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.12"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: GPU :: NVIDIA CUDA :: 13",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["torch==2.11.0", "torchvision==0.26.0", "wandb>=0.26.1"]

[project.optional-dependencies]
mjlab = ["mjlab>=1.5.3"]
isaac = ["isaaclab[all,isaacsim]==3.0.0b2.post1", "tinyobjloader==2.0.0rc13"]

[project.urls]
repository = "https://github.com/Achronus/velora"
documentation = "https://velora.achronus.dev"
issues = "https://github.com/Achronus/velora/issues"

[dependency-groups]
dev = ["pytest>=8.3.0"]
docs = ["mkdocs>=1.6.1", "mkdocs-material==9.7.7", "mkdocstrings-python==2.0.5"]
skrl = ["skrl>=2.1.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
stubPath = "typings"

[tool.setuptools.packages.find]
include = ["velora*"]

[tool.uv]
conflicts = [[{ extra = "mjlab" }, { extra = "isaac" }]]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cuda", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cuda", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
isaaclab = [{ index = "nvidia" }]
