[project]
name = "velora"
version = "0.3.0"
description = "A Liquid Reinforcement Learning (RL) framework for robotics."
authors = [{ name = "Ryan Partridge", email = "codemonkey37@proton.me" }]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.12"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: GPU :: NVIDIA CUDA :: 13",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "array-api-compat>=1.15.0",
    "isaaclab[all,isaacsim]==3.0.0b2.post1",
    "shimmy[dm-control]>=2.0.1",
    "torch==2.11.0",
    "torchvision==0.26.0",
    "wandb>=0.26.1",
]

[project.urls]
repository = "https://github.com/Achronus/velora"
documentation = "https://velora.achronus.dev"
issues = "https://github.com/Achronus/velora/issues"

[dependency-groups]
docs = ["mkdocs>=1.6.1", "mkdocs-material==9.7.6", "mkdocstrings-python==2.0.5"]

[tool.setuptools.packages.find]
include = ["velora*"]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cuda", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cuda", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
isaacsim = [
    { index = "nvidia", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
isaaclab = [{ index = "nvidia" }]
