name: Codecov Reporting

on:
  push:
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Testing Docker Image
        run: |
          docker pull ghcr.io/achronus/velora-testdeps:latest

      - name: Run tests and collect coverage
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            ghcr.io/achronus/velora-testdeps:latest \
            pytest --cov=velora --cov-report xml tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
